---

linters:
  Indentation:
    enabled: true
    character: space
    width: 2

  DeclarationOrder:
    enabled: false

  Comment:
    enabled: true
    allowed: '/*doc'

  VendorPrefix:
    enabled: false

  NameFormat:
    enabled: true
    convention: hyphenated_lowercase

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM

  PlaceholderInExtend:
    enabled: false

  NestingDepth:
    max_depth: 4
    ignore_parent_selectors: true

  PropertyUnits:
    global: ['rem','em','%','s', 'vh']
