version: "3.3"

services:
  website:
    ports:
      - "8000:8000"
      - "3001:3001"  # browserSync
      - "9000:9000"  # storybook
    working_dir: /website
    command: /bin/bash -c "npm install && npm start"