name: Build
on:
  push:
    branches:
      - "*"
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Image
        run: docker-compose up -d

      - name: Clean & Build
        run: docker-compose run website make -C production/ clean package

      - name: Store Artifact
        uses: actions/upload-artifact@v3
        with:
          name: biteme-website # double zipping issue: https://github.com/actions/upload-artifact/issues/39
          path: production/release/biteme-website.zip

      - name: Release
        run: make -C production/ release AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          --data '{"ref": "refs/heads/master"}' \
          https://api.github.com/repos/snake-biteme/snake_infrastructure/actions/workflows/website.yml/dispatches
